sudo: true
dist: trusty
before_install:
- sudo apt-get install nodejs-legacy
- sudo apt-get install build-essential
- sudo apt-get install npm
- sudo npm install -g n
- sudo n stable
language: node_js
node_js:
  - "7"
install:
- npm install
- npm install electron --save -dev
script:
- npm start
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: '*'
  skip_cleanup: true
  on:
    repo: akansh97531/Snipper
    tags: true