sudo: true
dist: trusty
before_install:
- sudo npm install -g npm
- sudo npm install --save electron
- sudo npm install -g npm@latest
- sudo npm install electron -g --verbose
language: node_js
node_js:
  - "7"
install:
- sudo npm install
- sudo npm install electron --save -dev
script:
- sudo npm start
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: '*'
  skip_cleanup: true
  on:
    repo: akansh97531/Snipper
    tags: true