sudo: true
dist: trusty
before_install:
- npm install -g npm@latest
language: node_js
node_js:
  - "7"
install:
- npm install
- npm install electron --save -dev
script:
- node main.js
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: '*'
  skip_cleanup: true
  on:
    repo: akansh97531/Snipper
    tags: true