sudo: required
os:
  - linux
  - osx
osx_image: xcode8.3
dist: trusty
language: node_js
node_js:
  - '8'
matrix:
  allow_failures:
    - os: osx
cache:
  - 'node_modules'
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];    then sudo add-apt-repository ppa:ubuntu-wine/ppa -y  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];    then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];    then sudo apt-get -qq update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];    then sudo apt-get install --no-install-recommends -y wine1.8 gcc-6 g++-6  ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];    then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];    then URL='http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.4_amd64.deb'; FILE=`mktemp`; wget "$URL" -qO $FILE && sudo dpkg -i $FILE; rm $FILE  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];    then sudo update-alternatives --set gcc /usr/bin/gcc-6  ; fi
install:
  - npm i -D
script:
  - 'npm i -D 7zip-bin'
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];    then npm run dist-mac          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];  then npm run dist-win          ; fi
